name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2.10.0
    - name: Build and Run the Docker image
      run: 
       docker build --file Dockerfile --tag flower .
       docker run --network container:flower 

      
      
      
      
