version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
  worker:
    build: ./
    entrypoint: celery
    command: -A tasks worker -l info -E
    user: nobody
    volumes:
      - ./examples:/data
    environment:
      CELERY_BROKER_URL: amqp://supreeth:supreeth_123@rabbitmq.sirpi.co.in:5672/localhost1
      CELERY_RESULT_BACKEND: mongodb+srv://supreeth:supreeth_123@sirpi.uv5ut.mongodb.net/sirpi?retryWrites=true&w=majority
      PYTHONPATH: /data
    depends_on:
      - web
      - worker1
      - worker2
      - flower1
      - flower2
  flower:
    build: ./
    command: celery -A tasks flower
    volumes:
      - ./examples:/data
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: amqp://supreeth:supreeth_123@rabbitmq.sirpi.co.in:5672/localhost1
      CELERY_RESULT_BACKEND: mongodb+srv://supreeth:supreeth_123@sirpi.uv5ut.mongodb.net/sirpi?retryWrites=true&w=majority
    depends_on:
      - web
      - worker1
      - worker2
      - flower1
      - flower2
