name: Docker Build & Push, Kubernetes Apply

on:
  push:
    branches: 
    - master

  workflow_dispatch:

jobs:
  build:
    runs-on: 

    steps:
    
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
           username: ${{ secrets.DH_USERNAME }}
           password: ${{ secrets.DH_PASSWORD }}
          
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          # Contents of kubeconfig file
          #kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Docker build & push, Kubernetes apply
        run: |
          docker build -t sahil222/flower .
          docker push sahil222/flower
          kubectl apply -f k8s.yaml
          #docker build -t ${{ secrets.DH_URL }}/levelupdevops:${{ github.sha }} .
          #docker push ${{ secrets.DH_URL }}/levelupdevops:${{ github.sha }}
          #sed -i'' -e 's/ACR_URL/${{ secrets.ACR_URL }}/g' -e 's/AKS_URL/${{ secrets.AKS_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
          #kubectl apply -f k8s.yaml
          
