name: main
on: 
 push:
   branches:
     - main
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: main
        run: docker run --network container:flower 
